name: Build and Release Resume
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: typst-community/setup-typst@v4

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install vendored fonts
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y fontconfig

          mkdir -p ~/.local/share/fonts
          cp fonts/PTSerif/*.ttf ~/.local/share/fonts/

          fc-cache -fv
          
      - name: Compile Resume
        # We move into the directory or point to the file path
        # Assuming resume_AriCholakin.typ is your main file
        run: typst-latest compile imprecv/resume_AriCholakin.typ resume_AriCholakin.pdf --font-path ~/.local/share/fonts

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Resume Build
          files: resume_AriCholakin.pdf
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}