name: Build and Release Resume
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: typst-community/setup-typst@v4

      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile Resume
        # We move into the directory or point to the file path
        # Assuming resume_AriCholakin.typ is your main file
        run: typst compile imprecv/resume_AriCholakian.typ resume.pdf --font-path fonts

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Resume Build
          files: resume.pdf
          make_latest: true
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}